# http://module-build.sourceforge.net/META-spec.html
#XXXXXXX This is a prototype!!!  It will change in the future!!! XXXXX#
name:         Class-DBI-Loader-Sybase
version:      0.01
version_from: lib/Class/DBI/Loader/Sybase.pm
installdirs:  site
requires:
    Class::DBI::Loader:            0
    Class::DBI::Sybase:            0
    DBD::Sybase:                   1.05

distribution_type: module
generated_by: ExtUtils::MakeMaker version 6.21
